[package]
name = "bevy_midi_browser"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
midir = "0.7.0"

console_error_panic_hook = "0.1.6"
web-sys = { version = "0.3", features = ["console", "Window"]}
js-sys = "0.3"
wasm-bindgen = "0.2"